--SQL Advance Case Study


--Q1--BEGIN 
--List all the states in which we have customers who have bought cellphones from 2005 till today.	
select STATE, DATE
FROM DIM_LOCATION A
INNER JOIN FACT_TRANSACTIONS B ON A. IDLocation= B. IDLocation
INNER JOIN DIM_MODEL C ON B. IDModel= C. IDModel
WHERE DATE BETWEEN '01-01-2005' AND GETDATE()

--Q1--END

--Q2--BEGIN
--What state in the US is buying the most 'Samsung' cell phones?

SELECT TOP 1 STATE
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_LOCATION B ON A. IDLocation= B.IDLocation
INNER JOIN DIM_MODEL C ON C. IDModel= A. IDModel
INNER JOIN DIM_MANUFACTURER D ON C. IDManufacturer= D. IDManufacturer
WHERE COUNTRY = 'US' AND Manufacturer_Name = 'SAMSUNG'
GROUP BY STATE
ORDER BY SUM (QUANTITY) DESC


--Q2--END

--Q3--BEGIN 
--Show the number of transactions for each model per zip code per state.

SELECT MODEL_NAME, ZIPCODE, STATE,  COUNT(IDCUSTOMER) AS CNT_TRANSACTION 
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_MODEL B ON A. IDModel=B.IDModel
INNER JOIN DIM_LOCATION C ON A. IDLocation=C. IDLocation
GROUP BY Model_Name, ZipCode, STATE
ORDER BY CNT_TRANSACTION DESC
	

--Q3--END

--Q4--BEGIN
--Show the cheapest cellphone (Output should contain the price also)

SELECT TOP 1 MANUFACTURER_NAME, MODEL_NAME, UNIT_PRICE
FROM DIM_MODEL A 
INNER JOIN DIM_MANUFACTURER B ON A. IDManufacturer= B. IDManufacturer
ORDER BY UNIT_PRICE 

--Q4--END

--Q5--BEGIN
--Find out the average price for each model in the top5 manufacturers in terms of sales quantity and order by average price.

SELECT Manufacturer_Name, MODEL_NAME, AVG (UNIT_PRICE) AS AVG_PRICE
FROM DIM_MODEL A 
INNER JOIN DIM_MANUFACTURER B ON A.IDManufacturer=B. IDManufacturer
WHERE Manufacturer_Name IN
(
SELECT TOP 5 MANUFACTURER_NAME
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_MODEL B ON A. IDModel= B. IDModel
INNER JOIN  DIM_MANUFACTURER C ON C. IDManufacturer =B.IDManufacturer
GROUP BY Manufacturer_Name
ORDER BY SUM(QUANTITY) DESC
)
GROUP BY  Manufacturer_Name, Model_Name
ORDER BY AVG_PRICE DESC

--Q5--END

--Q6--BEGIN
--List the names of the customers and the average amount spent in 2009, where the average is higher than 500

SELECT CUSTOMER_NAME, AVG(TOTALPRICE) AS AVG_AMOUNT
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_CUSTOMER B ON A.IDCustomer=B.IDCustomer
WHERE YEAR(DATE) = '2009'
GROUP BY Customer_Name
HAVING AVG(TOTALPRICE) >500
ORDER BY AVG_AMOUNT DESC

--Q6--END
	
--Q7--BEGIN  
	
--List if there is any model that was in the top 5 in terms of quantity, simultaneously in 2008, 2009 and 2010	

--SELECT IDMODEL, MODEL_NAME
--FROM DIM_MODEL
--WHERE Model_Name IN
--(
--SELECT TOP 5 Model_Name
--FROM FACT_TRANSACTIONS A
--INNER JOIN DIM_MODEL B ON A.IDModel =B.IDModel
--WHERE YEAR(DATE) IN ('2008','2009','2010')
--GROUP BY MODEL_NAME
--ORDER BY SUM(QUANTITY) DESC
--)
--GROUP BY Model_Name
--ORDER BY MODEL_NAME


SELECT MODEL_NAME 
FROM FACT_TRANSACTIONS
INNER JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDMODEL= DIM_MODEL.IDMODEL
GROUP BY MODEL_NAME
HAVING 
SUM(QUANTITY) >= ALL(SELECT TOP 5 SUM(QUANTITY) FROM FACT_TRANSACTIONS WHERE YEAR(DATE) = 2008  GROUP BY IDMODEL ORDER BY SUM(QUANTITY) DESC) AND 
SUM(QUANTITY) >= ALL(SELECT TOP 5 SUM(QUANTITY) FROM FACT_TRANSACTIONS WHERE YEAR(DATE) = 2009  GROUP BY IDMODEL ORDER BY SUM(QUANTITY) DESC) AND 
SUM(QUANTITY) >= ALL(SELECT TOP 5 SUM(QUANTITY) FROM FACT_TRANSACTIONS WHERE YEAR(DATE) = 2010  GROUP BY IDMODEL ORDER BY SUM(QUANTITY) DESC)

--Q7--END

--Q8--BEGIN
--Show the manufacturer with the 2nd top sales in the year of 2009 and the manufacturer with the 2nd top sales in the year of 2010.

WITH RESULT AS
(
SELECT MANUFACTURER_NAME, DENSE_RANK OVER (ORDER BY AMOUNT_SALES DESC) DENSERANK
FROM
(SELECT TOP 2 MANUFACTURER_NAME, SUM(TOTALPRICE) AMOUNT_SALES
FROM DIM_MANUFACTURER A 
INNER JOIN DIM_MODEL B ON A. IDManufacturer = B.IDManufacturer
INNER JOIN FACT_TRANSACTIONS C ON C. IDModel = B.IDModel
WHERE YEAR(DATE)='2009'
GROUP BY MANUFACTURER_NAME
ORDER BY SUM(TOTALPRICE) DESC) 
)
SELECT MANUFACTURER_NAME
FROM RESULT
WHERE RESULT.DENSERANK = 2




SELECT TOP 2 MANUFACTURER_NAME
FROM DIM_MANUFACTURER A 
INNER JOIN DIM_MODEL B ON A. IDManufacturer = B.IDManufacturer
INNER JOIN FACT_TRANSACTIONS C ON C. IDModel = B.IDModel
WHERE YEAR(DATE)='2010'
GROUP BY MANUFACTURER_NAME
ORDER BY SUM(TOTALPRICE) DESC 




--Q8--END
--Q9--BEGIN
--Show the manufacturers that sold cellphones in 2010 but did not in 2009.	

SELECT MANUFACTURER_NAME
FROM DIM_MANUFACTURER A
INNER JOIN DIM_MODEL B ON A. IDManufacturer=B.IDManufacturer
INNER JOIN FACT_TRANSACTIONS C ON C. IDModel= B. IDModel
WHERE YEAR(DATE) = 2010 
EXCEPT 
SELECT MANUFACTURER_NAME 
FROM DIM_MANUFACTURER A
INNER JOIN DIM_MODEL B ON A.IDMANUFACTURER= B.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS C ON C.IDMODEL= B.IDMODEL
WHERE YEAR(DATE) = 2009

--Q9--END

--Q10--BEGIN
	
--Find top 100 customers and their average spend, average quantity by each year. Also find the percentage of change in their spend.


SELECT TOP 100 CUSTOMER_NAME, 
AVG(CASE WHEN YEAR(DATE) = 2005 THEN TOTALPRICE END) AS AVERAGE_PRICE_2005,
AVG(CASE WHEN YEAR(DATE) = 2005 THEN QUANTITY END) AS AVERAGE_QTY_2005,
AVG(CASE WHEN YEAR(DATE) = 2018 THEN TOTALPRICE END) AS AVERAGE_PRICE_2018,
AVG(CASE WHEN YEAR(DATE) = 2018 THEN QUANTITY END) AS AVERAGE_QTY_2018
FROM DIM_CUSTOMER
INNER JOIN FACT_TRANSACTIONS T1 ON T1.IDCUSTOMER= DIM_CUSTOMER.IDCUSTOMER
GROUP BY CUSTOMER_NAME


SELECT TOP 100 B.CUSTOMER_NAME, YEAR(DATE) YEAR, AVG(TOTALPRICE) AVG_SPEND, AVG(QUANTITY) AVG_QTY
FROM FACT_TRANSACTIONS A
INNER JOIN DIM_CUSTOMER B ON A. IDCustomer=B.IDCustomer
GROUP BY CUSTOMER_NAME, YEAR(DATE)
ORDER BY YEAR(DATE)


--Q10--END
	