
/* Name - Pawan Saini*/

create database Retail_Analysis


/*   Data preparation and understanding     */

--1. what is the total number of rows in each of 3 tables in the database?

select 'customer' as Table_name, count(*)Count_of_rows
from Customer
union
select 'prod_cat_info' as Table_name , count(*)
from Prod_cat_info
union
select 'transactions' as Table_name ,count(*)
from Transactions


--2.	What is the total number of transactions that have a return?

select count(*) return_transactions
from transactions
where Qty < 0

--3.	As you would have noticed, the dates provided across the datasets are not in a correct format. As first steps, pls convert the date variables into valid date formats before proceeding ahead.


 SELECT CONVERT(varchar, tran_date,103) as tran_dt
  FROM Transactions

 

--4.	What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.

SELECT 
    MIN(tran_date) AS Start_tran_Date,
    MAX(tran_date) AS End_tran_Date,
       DATEDIFF(YEAR, MIN(tran_date),MAX(tran_date)) as Difference_Years,
       DATEDIFF(MONTH, MIN(TRAN_DATE), MAX(TRAN_DATE)) AS Difference_Month,
	   DATEDIFF(DAY, MIN(TRAN_DATE), MAX(TRAN_DATE)) AS Difference_Days
FROM Transactions


--5.	Which product category does the sub-category “DIY” belong to?

select prod_cat
from prod_cat_info
where prod_subcat = 'DIY'

        /*    DATA ANALYSIS    */

--1.	Which channel is most frequently used for transactions?

SELECT  top 1 Store_type, COUNT(*) AS cnt
FROM Transactions 
group by Store_type
order by cnt desc

--2.	What is the count of Male and Female customers in the database?

Select Gender, count(*) as CNT
from customer
WHERE gender in ('M' , 'F')
group by gender
order by gender desc

--3.	From which city do we have the maximum number of customers and how many?

select top 1 city_code, count(*) as cnt
from Customer
group by city_code
order by cnt desc


--4.	How many sub-categories are there under the Books category?

SELECT COUNT(PROD_SUBCAT) AS SUBCAT_CNT
FROM prod_cat_info
WHERE PROD_CAT = 'BOOKS'
GROUP BY PROD_CAT

--5.	What is the maximum quantity of products ever ordered?

SELECT 
TOP 1
a. PROD_CAT_CODE, PROD_CAT PRD_CAT , COUNT(a.PROD_CAT_CODE) QUANTITY
FROM Transactions a
LEFT JOIN prod_cat_info b ON a.PROD_CAT_CODE = b. PROD_CAT_CODE
GROUP BY a. PROD_CAT_CODE, PROD_CAT
ORDER BY 3 DESC 


--6.	What is the net total revenue generated in categories Electronics and Books?


SELECT Round(SUM(TOTAL_AMT),2) AMOUNT
FROM TRANSACTIONS A
INNER JOIN prod_cat_info B ON A.PROD_CAT_CODE = B.PROD_CAT_CODE 
AND B.PROD_SUB_CAT_CODE = A.PROD_SUBCAT_CODE
WHERE PROD_CAT IN ('BOOKS' , 'ELECTRONICS')


--7.	How many customers have >10 transactions with us, excluding returns?


SELECT COUNT(CUSTOMER_ID) AS CUSTOMER_COUNT
FROM CUSTOMER WHERE CUSTOMER_ID IN 
(
SELECT CUST_ID
FROM TRANSACTIONS A 
LEFT JOIN CUSTOMER B ON B. CUSTOMER_ID = A. CUST_ID
WHERE TOTAL_AMT NOT LIKE '-%'
GROUP BY
CUST_ID
HAVING 
COUNT(TRANSACTION_ID) > 10
)


--8.	What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?

SELECT SUM(TOTAL_AMT) as REVENUE
FROM Transactions A
INNER JOIN prod_cat_info B ON A. prod_cat_code=B.prod_cat_code AND A.prod_subcat_code=B.prod_sub_cat_code
WHERE prod_cat IN ('ELECTRONICS', 'CLOTHING') AND STORE_TYPE = 'FLAGSHIP STORE'


--9.	What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.

SELECT PROD_SUBCAT, SUM(TOTAL_AMT) AS REVENUE
FROM Transactions A
LEFT JOIN CUSTOMER B ON A.cust_id=B.customer_Id
LEFT JOIN prod_cat_info C ON C.prod_cat_code=A.prod_cat_code AND C. prod_sub_cat_code=A.prod_subcat_code
WHERE prod_cat='ELECTRONICS' AND GENDER = 'M'
GROUP BY prod_subcat
order by 2 desc


--10.	What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?

SELECT TOP 5 with ties
PROD_SUBCAT, ROUND(((SUM(TOTAL_AMT)/(SELECT SUM(TOTAL_AMT) FROM TRANSACTIONS))*100),2) AS PERCANTAGE_OF_SALES, 
cast((abs(sum(CASE WHEN QTY< 0 THEN QTY ELSE NULL END))) as float)/(select cast(SUM(abs(QTY)) as float) from Transactions)*100 AS PERCENTAGE_OF_RETURN
FROM TRANSACTIONS A
INNER JOIN prod_cat_info B ON A.PROD_CAT_CODE = B.PROD_CAT_CODE AND PROD_SUBCAT_CODE= PROD_SUB_CAT_CODE
GROUP BY PROD_SUBCAT
ORDER BY SUM(TOTAL_AMT) DESC


--11.	For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?


SELECT CUST_ID,Round(SUM(TOTAL_AMT),2) AS REVENUE FROM TRANSACTIONS
WHERE CUST_ID IN 
	(SELECT CUSTOMER_ID
	 FROM CUSTOMER
     WHERE DATEDIFF(YEAR,DOB,GETDATE()) BETWEEN 25 AND 35)
	 AND TRAN_DATE BETWEEN DATEADD(DAY,-30,(SELECT MAX(TRAN_DATE) FROM Transactions))
	 AND (SELECT MAX(TRAN_DATE) FROM TRANSACTIONS)
GROUP BY CUST_ID


--12.	Which product category has seen the max value of returns in the last 3 months of transactions?

SELECT TOP 1 PROD_CAT, Round(SUM(TOTAL_AMT),2) Value_return
FROM TRANSACTIONS A
INNER JOIN prod_cat_info B ON A. prod_cat_code=B.prod_cat_code AND A. prod_subcat_code= B.prod_sub_cat_code
WHERE TOTAL_AMT<0
AND TRAN_DATE BETWEEN DATEADD(MONTH, -3, (SELECT MAX(TRAN_DATE) FROM Transactions)) 
AND (SELECT MAX(TRAN_DATE) FROM Transactions)
GROUP BY PROD_CAT
ORDER BY 2 

--13.	Which store-type sells the maximum products; by value of sales amount and by quantity sold?

SELECT TOP 1 STORE_TYPE, SUM(TOTAL_AMT) TOT_SALES, SUM(QTY) TOT_QUAN
FROM TRANSACTIONS
GROUP BY STORE_TYPE
ORDER BY TOT_SALES DESC, TOT_QUAN DESC


--14.	What are the categories for which average revenue is above the overall average.

SELECT PROD_CAT, Round(AVG(TOTAL_AMT),2) AVG_REV
FROM Transactions A
INNER JOIN prod_cat_info B ON A.prod_cat_code=B.prod_cat_code AND A. prod_subcat_code=B. prod_sub_cat_code
GROUP BY PROD_CAT
HAVING AVG(TOTAL_AMT)> (SELECT AVG(TOTAL_AMT) FROM TRANSACTIONS)
ORDER BY 2 DESC

--15.	Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.

SELECT PROD_CAT, PROD_SUBCAT, AVG(TOTAL_AMT) AVG_REV, SUM(TOTAL_AMT) TOT_REV
FROM TRANSACTIONS A
INNER JOIN prod_cat_info B ON A. prod_cat_code=B.prod_cat_code AND A. prod_subcat_code=B. prod_sub_cat_code
WHERE PROD_CAT IN 
(SELECT TOP 5 PROD_CAT
FROM TRANSACTIONS A
INNER JOIN prod_cat_info B ON A. prod_cat_code = B. prod_cat_code AND A. prod_subcat_code = B. prod_sub_cat_code
GROUP BY PROD_CAT
ORDER BY SUM(QTY) DESC)
GROUP BY PROD_CAT, PROD_SUBCAT
order by prod_cat, prod_subcat



/* END of Query */